### Successful Login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

###

### Incorrect Password
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "wrongpassword"
}

###

### User Not Found
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "nonexistentuser@example.com",
  "password": "password123"
}

###

### Missing Email
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "password": "password123"
}

###

### Missing Password
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com"
}

###

### Invalid Email Format
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "invalidemail",
  "password": "password123"
}




### Get Profile Request
GET http://localhost:4000/auth/profile
Cookie: token=<insert-auth-token-here>


### Logout Request
POST http://localhost:4000/auth/logout
Cookie: token=<insert-auth-token-here>
